DELETE FROM Question;
	DELETE FROM Answer;
INSERT INTO Question (id,realm,type,text) OVERRIDING SYSTEM VALUE VALUES (0,'java',2,'');
INSERT INTO Question (id,realm,type,text) OVERRIDING SYSTEM VALUE VALUES (1,'java',2,'qweqweqwe');
INSERT INTO Question (id,realm,type,text) OVERRIDING SYSTEM VALUE VALUES (2,'kotlin',2,'adsd');
INSERT INTO Question (id,realm,type,text) OVERRIDING SYSTEM VALUE VALUES (3,'kotlin',2,'Тут были кракозябры');
	INSERT INTO Answer (id,questionId,text,correct) OVERRIDING SYSTEM VALUE VALUES (16,3,'Верный ответ',true);
	INSERT INTO Answer (id,questionId,text,correct) OVERRIDING SYSTEM VALUE VALUES (13,3,'Неверный ответ',false);
	INSERT INTO Answer (id,questionId,text,correct) OVERRIDING SYSTEM VALUE VALUES (14,3,'Более-менее ответ',true);
	INSERT INTO Answer (id,questionId,text,correct) OVERRIDING SYSTEM VALUE VALUES (15,3,'Неверный ответ',false);
INSERT INTO Question (id,realm,type,text) OVERRIDING SYSTEM VALUE VALUES (4,'java',0,'ÑÑÐ²ÑÑÐ²');
INSERT INTO Question (id,realm,type,text) OVERRIDING SYSTEM VALUE VALUES (5,'java',0,'сячсч');
INSERT INTO Question (id,realm,type,text) OVERRIDING SYSTEM VALUE VALUES (6,'kotlin',1,'Rjnkby Колтин!');
INSERT INTO Question (id,realm,type,text) OVERRIDING SYSTEM VALUE VALUES (7,'java',0,'фвывфыв');
INSERT INTO Question (id,realm,type,text) OVERRIDING SYSTEM VALUE VALUES (8,'java',0,'фвывфыв');
INSERT INTO Question (id,realm,type,text) OVERRIDING SYSTEM VALUE VALUES (9,'java',0,'');
INSERT INTO Question (id,realm,type,text) OVERRIDING SYSTEM VALUE VALUES (10,'java',0,'');
INSERT INTO Question (id,realm,type,text) OVERRIDING SYSTEM VALUE VALUES (11,'java',0,'');
INSERT INTO Question (id,realm,type,text) OVERRIDING SYSTEM VALUE VALUES (12,'java',0,'');
INSERT INTO Question (id,realm,type,text) OVERRIDING SYSTEM VALUE VALUES (13,'java',0,'');
INSERT INTO Question (id,realm,type,text) OVERRIDING SYSTEM VALUE VALUES (14,'java',0,'');
INSERT INTO Question (id,realm,type,text) OVERRIDING SYSTEM VALUE VALUES (15,'kotlin',2,'ОЛОФВЛЫ');
INSERT INTO Question (id,realm,type,text) OVERRIDING SYSTEM VALUE VALUES (16,'kotlin',2,'ОЛОФВЛЫ');
INSERT INTO Question (id,realm,type,text) OVERRIDING SYSTEM VALUE VALUES (17,'java',0,'');
INSERT INTO Question (id,realm,type,text) OVERRIDING SYSTEM VALUE VALUES (18,'java',0,'');
	INSERT INTO Answer (id,questionId,text,correct) OVERRIDING SYSTEM VALUE VALUES (0,18,'qwe',false);
	INSERT INTO Answer (id,questionId,text,correct) OVERRIDING SYSTEM VALUE VALUES (1,18,'asd',false);
	INSERT INTO Answer (id,questionId,text,correct) OVERRIDING SYSTEM VALUE VALUES (2,18,'rty',true);
	INSERT INTO Answer (id,questionId,text,correct) OVERRIDING SYSTEM VALUE VALUES (3,18,'fgh',false);
INSERT INTO Question (id,realm,type,text) OVERRIDING SYSTEM VALUE VALUES (19,'kotlin',1,'sf sfлор лорывлор ыва');
INSERT INTO Question (id,realm,type,text) OVERRIDING SYSTEM VALUE VALUES (20,'java',0,'лорл лор фыв');
	INSERT INTO Answer (id,questionId,text,correct) OVERRIDING SYSTEM VALUE VALUES (4,20,'апрпа',false);
	INSERT INTO Answer (id,questionId,text,correct) OVERRIDING SYSTEM VALUE VALUES (6,20,'рпарим',false);
	INSERT INTO Answer (id,questionId,text,correct) OVERRIDING SYSTEM VALUE VALUES (7,20,'иь',false);
INSERT INTO Question (id,realm,type,text) OVERRIDING SYSTEM VALUE VALUES (21,'java',0,'213234234');
	INSERT INTO Answer (id,questionId,text,correct) OVERRIDING SYSTEM VALUE VALUES (8,21,'ываыу',false);
	INSERT INTO Answer (id,questionId,text,correct) OVERRIDING SYSTEM VALUE VALUES (9,21,'',false);
	INSERT INTO Answer (id,questionId,text,correct) OVERRIDING SYSTEM VALUE VALUES (10,21,'',false);
	INSERT INTO Answer (id,questionId,text,correct) OVERRIDING SYSTEM VALUE VALUES (11,21,'',false);
INSERT INTO Question (id,realm,type,text) OVERRIDING SYSTEM VALUE VALUES (22,'java',0,'77777');
	INSERT INTO Answer (id,questionId,text,correct) OVERRIDING SYSTEM VALUE VALUES (12,22,'ППП',false);
INSERT INTO Question (id,realm,type,text) OVERRIDING SYSTEM VALUE VALUES (23,'java',0,'');
